### ISSUE TITLE
Unable to use the draw section 

### ISSUE THREAD

**Issue by Alhaider** [lext/PyCon2016#2]
I tried the code and it worked perfectly except for the section where I have to draw. As suggested I ran the javascript on chrome debug and I got the following error on file bootstrap.min.js

Uncaught Error: Bootstrap's JavaScript requires jQuery
    at <anonymous>:6:37

**Comment by lext** [comment]
Just did the fresh installation and everything works. Are you running this in Windows? I think that that there might be some problem with the paths in the case.

**Comment by Alhaider** [comment]
No I am using mac, if its not the HTML my only guess it's the layout of the JavaScript, I never worked with JavaScript.

**Comment by lext** [comment]
I will test it on my Mac ASAP.

**Comment by lext** [comment]
@Alhaider I tested the code with the fresh virtualenv on Mac and it works. Check your installed packages.
