### ISSUE TITLE
Can't recognize Digits

### ISSUE THREAD

**Issue by Shraddha2702** [lext/PyCon2016#3]
I have implemented the project locally 
But no matter what number I draw, It recognizes only "7" 
I tried restarting it again, but still the same results
What exactly is the error here?    
  
Here's the Screenshots !  
 
![screenshot 99](https://user-images.githubusercontent.com/20888124/27326156-5a82d55a-55c8-11e7-86f6-f9776cc257b8.png)
![screenshot 104](https://user-images.githubusercontent.com/20888124/27326158-5a86c1c4-55c8-11e7-932c-89286886befe.png)
![screenshot 112](https://user-images.githubusercontent.com/20888124/27326159-5a87cb82-55c8-11e7-8332-c34433a7d7c4.png)
![screenshot 113](https://user-images.githubusercontent.com/20888124/27326160-5a8a1b30-55c8-11e7-914d-84ecb2b1e8a9.png)
![screenshot 114](https://user-images.githubusercontent.com/20888124/27326157-5a854aa6-55c8-11e7-88d8-bb94e6484e60.png)

**Comment by lext** [comment]
Hi, you just need to import function `make_mnist` from `utils.py` module, and use it instead of resizing in https://github.com/lext/PyCon2016/blob/master/digits_classifier/srv.py#L26. It was in my talk on YouTube :-)

**Comment by Shraddha2702** [comment]
Yes i did watch your YT video.. that's how I got here.. :)
n I had already added that line in the code which gave the above result

**Comment by lext** [comment]
@Shraddha2702 I couldn't reproduce your bug. Check whether everything is installed correctly. I also inserted make_mnist call where it should be to reduce the further confusions.

I recommend you to create a virtual environment. Please find the screenshots from my browser that I just produced below:

<img width="754" alt="screen shot 2017-07-12 at 13 35 28" src="https://user-images.githubusercontent.com/4714134/28113969-6ef132b6-6707-11e7-9d3f-9717a35e2a10.png">
<img width="791" alt="screen shot 2017-07-12 at 13 34 51" src="https://user-images.githubusercontent.com/4714134/28113967-6eeec88c-6707-11e7-9372-2d8a770b4e1a.png">
<img width="766" alt="screen shot 2017-07-12 at 13 34 21" src="https://user-images.githubusercontent.com/4714134/28113970-6ef22784-6707-11e7-80c9-ee5559777abf.png">
<img width="794" alt="screen shot 2017-07-12 at 13 34 13" src="https://user-images.githubusercontent.com/4714134/28113971-6ef2608c-6707-11e7-9998-6a565ad4a4fa.png">
<img width="858" alt="screen shot 2017-07-12 at 13 34 02" src="https://user-images.githubusercontent.com/4714134/28113968-6eef49ec-6707-11e7-8bb7-dd90f813aa5e.png">
